meta_product_name: "2Bridal"
meta_title: "2Bridal. Find your dream dress without breaking the bank"
meta_description: "Rent out slightly used designer wedding dresses from hundreds of name brands for a fraction of their retail cost"
meta_image: "designer1.jpg" # should exist in `app/assets/images/`
# twitter_account: ""   # required for Twitter Cards
